// @generated — DO NOT EDIT.
// Source: packages/caws-cli/surfaces/registry.json (version 1).
// Regenerated by scripts/generate-surface-registry.mjs; the build fails when
// this file drifts from the registry (check-surface-registry.mjs).
// CAWS-DESIGN-GLOBAL-IDENTITY-HOME-001 A2: one registry edit adds a surface.

export type AgentSurface = 'claude-code' | 'codex' | 'opencode' | 'zcode' | 'kimi-code' | 'qwen-code' | 'dsh' | 'cursor' | 'windsurf' | 'none';

export const AGENT_SURFACES: readonly AgentSurface[] = ['claude-code', 'codex', 'opencode', 'zcode', 'kimi-code', 'qwen-code', 'dsh', 'cursor', 'windsurf', 'none'];

/** Per-surface session-identity env vars, in precedence order. */
export const SURFACE_ENV_VARS: Readonly<Record<AgentSurface, readonly string[]>> = {
  'claude-code': ['CLAUDE_SESSION_ID', 'CLAUDE_CODE_SESSION_ID'],
  'codex': ['CODEX_THREAD_ID'],
  'opencode': [],
  'zcode': [],
  'kimi-code': [],
  'qwen-code': ['QWEN_CODE_SESSION_ID'],
  'dsh': ['DSH_SESSION_ID'],
  'cursor': ['CURSOR_TRACE_ID'],
  'windsurf': [],
  'none': [],
};

/** The env var the surface pin prefers when CAWS_AGENT_SURFACE names the
 *  platform. Absent for surfaces with no per-session env var. */
export const SURFACE_PIN_VARS: Readonly<Partial<Record<AgentSurface, string>>> = {
  'claude-code': 'CLAUDE_SESSION_ID',
  'codex': 'CODEX_THREAD_ID',
  'qwen-code': 'QWEN_CODE_SESSION_ID',
  'dsh': 'DSH_SESSION_ID',
};

/** Trust-gated surfaces: project-scope wiring can be silently disabled by the
 *  harness (see the registry's trustGated field). */
export const TRUST_GATED_SURFACES: readonly AgentSurface[] = ['zcode', 'qwen-code'];

/** The hook mechanism each harness exposes (shell-hooks, js-plugin, ...). */
export const SURFACE_HOOK_MECHANISMS: Readonly<Record<AgentSurface, string>> = {
  'claude-code': 'shell-hooks',
  'codex': 'shell-hooks',
  'opencode': 'js-plugin',
  'zcode': 'shell-hooks',
  'kimi-code': 'user-toml',
  'qwen-code': 'shell-hooks',
  'dsh': 'harness-plugin',
  'cursor': 'shell-hooks',
  'windsurf': 'shell-hooks',
  'none': 'none',
};

/** The sentinel surface ('none'): generic identity, no harness. */
export const SENTINEL_SURFACE: AgentSurface = 'none';
