'use strict';
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { spawnSync } = require('node:child_process');
const Ajv = require('ajv/dist/2020');
const addFormats = require('ajv-formats');
const packageRoot = path.resolve(__dirname, '../..');
const temporary = [];
function fixture() {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'caws-artifact-contract-'));
  temporary.push(root);
  return root;
}
function write(root, relative, bytes) {
  const target = path.join(root, relative);
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(target, bytes);
}
function retain(name, bytes) {
  if (process.env.CAWS_RELEASE_ARTIFACT_DIR)
    write(process.env.CAWS_RELEASE_ARTIFACT_DIR, name, bytes);
}
afterAll(() => temporary.forEach((root) => fs.rmSync(root, { recursive: true, force: true })));

test('worker setup removes inherited session authority and preserves artifact destinations', () => {
  const setup = path.join(packageRoot, 'tests/helpers/isolate-session-env.js');
  const result = spawnSync(
    process.execPath,
    [
      '-e',
      'require(process.argv[1]); console.log(JSON.stringify({thread:process.env.CODEX_THREAD_ID,home:process.env.CAWS_HOME,kill:process.env.CAWS_TRAP_KILL,artifacts:process.env.CAWS_RELEASE_ARTIFACT_DIR}))',
      setup,
    ],
    {
      encoding: 'utf8',
      env: {
        ...process.env,
        CODEX_THREAD_ID: 'live-parent',
        CAWS_HOME: '/foreign/home',
        CAWS_TRAP_KILL: '1',
        CAWS_RELEASE_ARTIFACT_DIR: '/fixture/artifacts',
      },
    }
  );
  expect(result.status).toBe(0);
  expect(JSON.parse(result.stdout)).toEqual({ artifacts: '/fixture/artifacts' });
});

test('actual npm files policy excludes planted bytecode while retaining executable templates', () => {
  const root = fixture();
  write(root, 'package.json', fs.readFileSync(path.join(packageRoot, 'package.json')));
  write(root, 'dist/index.js', 'console.log("fixture");\n');
  write(root, 'templates/hook-packs/shared/runtime.py', 'print("source")\n');
  write(
    root,
    'templates/hook-packs/shared/__pycache__/runtime.cpython-314.pyc',
    'generated bytecode'
  );
  write(root, 'templates/hook-packs/shared/loose.pyc', 'generated bytecode');
  write(root, 'templates/hook-packs/shared/loose.pyo', 'generated bytecode');
  const result = spawnSync(
    'npm',
    [
      'pack',
      '--dry-run',
      '--ignore-scripts',
      '--json',
      '--workspaces=false',
      '--cache',
      path.join(root, 'cache'),
    ],
    { cwd: root, encoding: 'utf8' }
  );
  expect({ status: result.status, stderr: result.stderr }).toEqual({ status: 0, stderr: '' });
  const files = JSON.parse(result.stdout)[0].files.map((file) => file.path);
  expect(files).toContain('templates/hook-packs/shared/runtime.py');
  expect(files).toContain('dist/index.js');
  expect(files.filter((file) => /__pycache__|\.py[co]$/.test(file))).toEqual([]);
  retain('pack-policy.json', result.stdout);
});

test('real renderer bytes validate with nullable summary and lineage; malformed shapes are rejected', () => {
  const root = fixture();
  const ts = '2026-10-03T12:00:00.000Z';
  const records = [
    {
      timestamp: ts,
      type: 'session_meta',
      payload: { id: 'renderer-contract', cwd: root, forked_from: 'fixture-parent' },
    },
    {
      timestamp: ts,
      type: 'response_item',
      payload: {
        type: 'message',
        role: 'user',
        content: [{ type: 'input_text', text: 'Verify the candidate.' }],
      },
    },
    {
      timestamp: ts,
      type: 'response_item',
      payload: {
        type: 'message',
        role: 'assistant',
        content: [{ type: 'output_text', text: 'Checked.' }],
      },
    },
  ];
  write(
    root,
    'transcript.jsonl',
    records.map((record) => JSON.stringify(record)).join('\n') + '\n'
  );
  const argv = [
    path.join(packageRoot, 'templates/hook-packs/shared/session_log_renderer.py'),
    path.join(root, 'turns'),
    root,
    'renderer-contract',
    ts,
    'fixture',
    'main',
    'abc123',
    '0',
    'abc123',
    path.join(root, 'transcript.jsonl'),
  ];
  const result = spawnSync('python3', argv, {
    encoding: 'utf8',
    env: { ...process.env, PYTHONDONTWRITEBYTECODE: '1' },
  });
  expect({ status: result.status, stderr: result.stderr }).toEqual({ status: 0, stderr: '' });
  const bytes = fs.readFileSync(path.join(root, 'turns/turn-001.json'), 'utf8');
  const payload = JSON.parse(bytes);
  const ajv = new Ajv({ allErrors: true, strict: true });
  addFormats(ajv);
  const validate = ajv.compile(require('../../src/kernel/schemas/telemetry/turn-log.v2.json'));
  expect({ valid: validate(payload), errors: validate.errors }).toEqual({
    valid: true,
    errors: null,
  });
  expect(payload.user).toBe('Verify the candidate.');
  expect(payload.turn_summary).toBeNull();
  expect(payload.context.lineage).toEqual({
    parent_session_id: 'fixture-parent',
    source: 'transcript_metadata',
    authority: 'none',
    source_path: path.join(root, 'transcript.jsonl'),
  });
  for (const invalid of [
    { ...payload, turn_summary: 42 },
    { ...payload, context: { ...payload.context, lineage: 'fabricated' } },
    { ...payload, status: 'fabricated' },
  ]) {
    expect(validate(invalid)).toBe(false);
  }
  retain('rendered-turn-001.json', bytes);
  retain(
    'renderer-receipt.json',
    JSON.stringify(
      {
        command: ['python3', ...argv],
        exit_status: result.status,
        stdout: result.stdout,
        stderr: result.stderr,
        valid: true,
      },
      null,
      2
    )
  );
  retain('renderer-transcript.jsonl', fs.readFileSync(path.join(root, 'transcript.jsonl')));
});
